-- ===========================================================================
-- Examples
-- ===========================================================================

target("error_demo")
    set_kind("binary")
    set_default(true)
    set_group("examples")
    set_targetdir("$(builddir)/$(plat)/$(arch)/$(mode)/examples")
    add_files("error_demo.cpp", "../src/error.cppm", "../src/logging.cppm", "../src/string_utils.cppm")
    set_policy("build.c++.modules", true)
    add_cxxflags("/utf-8", {tools = "cl"})
target_end()

target("string_utils_demo")
    set_kind("binary")
    set_default(true)
    set_group("examples")
    set_targetdir("$(builddir)/$(plat)/$(arch)/$(mode)/examples")
    add_files("string_utils_demo.cpp", "../src/string_utils.cppm", "../src/error.cppm", "../src/logging.cppm")
    set_policy("build.c++.modules", true)
    add_cxxflags("/utf-8", {tools = "cl"})
target_end()

target("file_system_demo")
    set_kind("binary")
    set_default(true)
    set_group("examples")
    set_targetdir("$(builddir)/$(plat)/$(arch)/$(mode)/examples")
    add_files("file_system_demo.cpp", "../src/file_system.cppm", "../src/error.cppm", "../src/logging.cppm", "../src/string_utils.cppm")
    set_policy("build.c++.modules", true)
    add_cxxflags("/utf-8", {tools = "cl"})
target_end()

target("logging_demo")
    set_kind("binary")
    set_default(true)
    set_group("examples")
    set_targetdir("$(builddir)/$(plat)/$(arch)/$(mode)/examples")
    add_files("logging_demo.cpp", "../src/logging.cppm", "../src/string_utils.cppm", "../src/error.cppm")
    set_policy("build.c++.modules", true)
    add_cxxflags("/utf-8", {tools = "cl"})
target_end()

target("test_demo")
    set_kind("binary")
    set_default(true)
    set_group("examples")
    set_targetdir("$(builddir)/$(plat)/$(arch)/$(mode)/examples")
    add_files("test_demo.cpp", "../src/test.cppm", "../src/logging.cppm", "../src/string_utils.cppm", "../src/error.cppm")
    set_policy("build.c++.modules", true)
    add_cxxflags("/utf-8", {tools = "cl"})
target_end()

target("time_utils_demo")
    set_kind("binary")
    set_default(true)
    set_group("examples")
    set_targetdir("$(builddir)/$(plat)/$(arch)/$(mode)/examples")
    add_files("time_utils_demo.cpp", "../src/time_utils.cppm", "../src/error.cppm", "../src/logging.cppm", "../src/string_utils.cppm")
    set_policy("build.c++.modules", true)
    add_cxxflags("/utf-8", {tools = "cl"})
target_end()

target("concurrent_demo")
    set_kind("binary")
    set_default(true)
    set_group("examples")
    set_targetdir("$(builddir)/$(plat)/$(arch)/$(mode)/examples")
    add_files("concurrent_demo.cpp", "../src/concurrent.cppm", "../src/error.cppm", "../src/logging.cppm", "../src/string_utils.cppm")
    set_policy("build.c++.modules", true)
    add_cxxflags("/utf-8", {tools = "cl"})
target_end()

target("math_utils_demo")
    set_kind("binary")
    set_default(true)
    set_group("examples")
    set_targetdir("$(builddir)/$(plat)/$(arch)/$(mode)/examples")
    add_files("math_utils_demo.cpp", "../src/math_utils.cppm", "../src/error.cppm", "../src/logging.cppm", "../src/string_utils.cppm")
    set_policy("build.c++.modules", true)
    add_cxxflags("/utf-8", {tools = "cl"})
target_end()

target("cli_demo")
    set_kind("binary")
    set_default(true)
    set_group("examples")
    set_targetdir("$(builddir)/$(plat)/$(arch)/$(mode)/examples")
    add_files("cli_demo.cpp", "../src/cli.cppm", "../src/string_utils.cppm", "../src/error.cppm", "../src/logging.cppm")
    set_policy("build.c++.modules", true)
    add_cxxflags("/utf-8", {tools = "cl"})
target_end()
